# Generated by Django 5.2.6 on 2026-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NECO', 'NECO'), ('POST_UTME', 'Post-UTME')], default='JAMB', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('english', 'English')], default='physics', max_length=50),
        ),
    ]
